# Generated by Django 5.2.3 on 2025-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sibsp', models.IntegerField(blank=True, null=True)),
                ('parch', models.IntegerField(blank=True, null=True)),
                ('pclass', models.IntegerField(blank=True, null=True)),
                ('cabin_symbol', models.CharField(blank=True, max_length=1, null=True)),
                ('embarked', models.CharField(blank=True, max_length=1, null=True)),
                ('home_dest', models.CharField(blank=True, max_length=255, null=True)),
                ('survived', models.BooleanField()),
            ],
        ),
    ]
